# Generated by Django 4.1 on 2022-10-12 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ebook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='rating',
        ),
    ]
