# Generated by Django 4.1 on 2022-10-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ebook', '0002_remove_books_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='book_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='book_name',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='books',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
