# Generated by Django 4.1 on 2022-10-13 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ebook', '0003_rename_book_title_books_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='title',
            new_name='book_title',
        ),
    ]
