# Generated by Django 4.1 on 2022-10-13 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ebook', '0004_rename_title_books_book_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='book',
            new_name='book_name',
        ),
    ]
